---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  namespace: imv-dev
spec:
  selector:
    matchLabels:
      run: imv-backend-service-dev
  replicas: 1
  template:
    metadata:
      labels:
        run: imv-backend-service-dev
      annotations:
        consul.sendo.vn/inject: "false"
        configmap.reloader.stakater.com/reload: "imv-backend-config"
    spec:
      volumes:
      - name: imv-backend-config-volume
        configMap:
          name: imv-backend-config
      - name: file-store
        persistentVolumeClaim:
          claimName: pvc-imv-dev
          readOnly: false
      containers:
        - name: imv-backend-service
          image: registry.1retail-dev.asia/imv-dev/backend-service:BUILD_NUMBER
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
          ports:
            - containerPort: 80
          volumeMounts:
            - name: imv-backend-config-volume
              mountPath: /app/config
            #- name: file-store
            #  mountPath: /app/dist/src
          resources:
            limits:
              cpu: '0.4'
              memory: 256Mi
            requests:
              cpu: '0.2'
              memory: 128Mi

          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 15"]
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: imv-dev
  labels:
    tier: golang_mod
    run: imv-backend-service-dev
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: imv-backend-service-http

  selector:
    run: imv-backend-service-dev

