version: '3.9'

services:
  mariadb-imv-backend-dev:
    image: mariadb:10.5.7
    restart: always
    container_name: mariadb-imv-backend-dev
    ports:
      - 7001:3306
    volumes:
      - "dms-database-dev:/data/db/imv"
    environment:
      - MYSQL_ROOT_PASSWORD=Juve@12345
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - dms-network
volumes:
  dms-database-dev:
    driver: local
networks:
  dms-network:
    external: true
    driver: bridge